"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

export type Language = "en" | "fa"

const translations = {
  en: {
    app_title: "jaliz",
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    my_plants: "My Plants",
    welcome_title: "Good morning, Sarah! 🪴",
    morning_greeting: "Good morning, Sarah! 🪴",
    afternoon_greeting: "Good afternoon, Sarah! 🪴",
    evening_greeting: "Good evening, Sarah! 🪴",
    night_greeting: "Good night, Sarah! 🪴",
    welcome_desc: "Here's what your garden needs today.",
    watering_title: "Watering Schedule",
    watering_desc: "3 plants need water today.",
    weather_title: "Hyper-Local Weather Advice",
    weather_desc: "AI-powered gardening advice based on your plants and local 48h forecast.",
    analyzing: "Analyzing weather risks...",
    generate_btn: "Generate Advice",
    generating_btn: "Generating...",
    advice_prompt: "Click below to generate actionable advice for your Monstera and Tomato plants.",
    market_title: "Nearby Marketplace",
    market_within: "Within 5km",
    contact_btn: "Contact via WhatsApp",
    away: "away",
    by: "by",
    add_plant: "Add Plant",
    add_new_plant: "Add a New Plant",
    plant_name: "Plant Name",
    plant_name_ph: "e.g., Monstera Deliciosa",
    plant_type: "Plant Type",
    plant_type_ph: "e.g., Indoor Tropical",
    location_type: "Location",
    location_indoor: "Indoor",
    location_outdoor: "Outdoor",
    light_exposure: "Light Exposure",
    light_low: "Low Light",
    light_partial: "Partial Shade",
    light_bright: "Bright Indirect",
    light_full: "Full Sun",
    pot_type: "Pot Type",
    pot_terracotta: "Terracotta",
    pot_plastic: "Plastic",
    pot_ceramic: "Ceramic",
    pot_metal: "Metal",
    pot_other: "Other",
    has_drainage: "Has Drainage Hole",
    last_watered: "Last Watered",
    recently_replanted: "Recently Replanted",
    plant_image: "Plant Image (Optional)",
    health_status: "Health Status",
    health_excellent: "Excellent",
    health_good: "Good",
    health_needs_attention: "Needs Attention",
    cancel: "Cancel",
    save: "Save Plant",
    no_plants: "You haven't added any plants yet.",
    watered_today: "Watered today",
    watered_days_ago: "days ago",
    care_tips: "Care Tips",
    care_tips_ph: "General care tips...",
    watering_tips: "Watering Tips",
    watering_tips_ph: "Watering schedule and tips...",
    settings: "Settings",
    api_key_title: "Gemini API Settings",
    api_key_desc: "Enter your Gemini API key to power the AI gardening advice.",
    api_key_label: "API Key",
    api_key_ph: "AIzaSy...",
    fetch_models: "Fetch Models",
    fetching: "Fetching...",
    select_model: "Select a Model",
    token_limit: "Token Limit",
    input_tokens: "Input",
    output_tokens: "Output",
    save_settings: "Save Settings",
    saved_successfully: "Settings saved successfully!",
    api_key_required: "API Key is required to generate advice.",
    user_location_title: "Your Location",
    user_location_label: "City, Country",
    user_location_ph: "e.g. Tehran, Iran",
    // Auth
    sign_in: "Sign in",
    sign_up: "Sign up",
    sign_out: "Sign out",
    account: "Account",
    admin_panel: "Admin",
    login_title: "Welcome back",
    login_desc: "Sign in to your jaliz account.",
    register_title: "Create your account",
    register_desc: "Join jaliz and start growing smarter.",
    email: "Email",
    email_ph: "you@example.com",
    password: "Password",
    password_ph: "At least 6 characters",
    confirm_password: "Confirm password",
    full_name: "Full name",
    full_name_ph: "Your full name",
    register_btn: "Create account",
    login_btn: "Sign in",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",
    auth_error_invalid_credentials: "Email or password is incorrect.",
    auth_error_email_exists: "An account with this email already exists.",
    auth_error_user_inactive: "This account has been disabled.",
    auth_error_user_not_found: "User not found.",
    auth_error_weak_password: "Password must be at least 6 characters.",
    auth_error_invalid_email: "Please enter a valid email address.",
    auth_error_empty_field: "Please fill in all required fields.",
    auth_error_password_mismatch: "Passwords do not match.",
    auth_error_generic: "Something went wrong. Please try again.",

    // Admin panel
    admin_title: "User Management",
    admin_desc: "Manage registered users, roles and access.",
    admin_search_ph: "Search by name or email…",
    admin_total_users: "Total users",
    admin_active_users: "Active",
    admin_admins: "Admins",
    admin_col_user: "User",
    admin_col_role: "Role",
    admin_col_status: "Status",
    admin_col_joined: "Joined",
    admin_col_actions: "Actions",
    admin_role_admin: "Admin",
    admin_role_user: "User",
    admin_status_active: "Active",
    admin_status_inactive: "Disabled",
    admin_action_reset: "Reset password",
    admin_action_delete: "Delete",
    admin_action_deactivate: "Disable",
    admin_action_activate: "Enable",
    admin_no_users: "No users match your search.",
    admin_confirm_delete: "Delete this user permanently? This cannot be undone.",
    admin_reset_title: "Reset password",
    admin_reset_desc: "Set a new password for {name}. They will need to use it on their next sign-in.",
    admin_reset_new_password: "New password",
    admin_reset_btn: "Set password",
    admin_reset_success: "Password updated.",
    admin_self_warning: "You can't change the role or disable your own account here.",
    admin_only: "This page is for administrators only.",
    go_home: "Go to dashboard",
    auth_required: "Please sign in to continue.",
    you_label: "(you)",
    // Admin AI API config
    admin_ai_title: "AI API Configuration",
    admin_ai_desc: "Set the Gemini API key used by all users for AI-powered features.",
    admin_ai_key_label: "Gemini API Key",
    admin_ai_key_ph: "AIzaSy...",
    admin_ai_fetch_models: "Verify & Fetch Models",
    admin_ai_select_model: "Default Model",
    admin_ai_save: "Save AI Settings",
    admin_ai_saved: "AI settings saved for all users!",
    admin_ai_no_key: "No API key configured yet.",
    // Landing page
    landing_hero_eyebrow: "Hyper-local AI gardening",
    landing_hero_title: "Grow happier plants, every season.",
    landing_hero_subtitle: "jaliz watches the weather, knows your plants, and tells you exactly what to do today — in plain English or Persian.",
    landing_cta_primary: "Create your free account",
    landing_cta_secondary: "Sign in",
    landing_hero_card_title: "Today's advice",
    landing_hero_card_line1: "Cold front tonight — move the Monstera away from the window.",
    landing_hero_card_line2: "Tomato is heading into full sun: water early, deeply.",
    landing_hero_card_badge: "AI generated",
    landing_trust_label: "Trusted by gardeners growing",
    landing_trust_chip_1: "Tropicals",
    landing_trust_chip_2: "Vegetables",
    landing_trust_chip_3: "Herbs",
    landing_trust_chip_4: "Succulents",
    landing_features_eyebrow: "Why jaliz",
    landing_features_title: "Everything a busy gardener needs",
    landing_features_subtitle: "One quiet companion that turns weather data, plant biology, and your neighborhood into clear next steps.",
    landing_feature_1_title: "AI weather advice",
    landing_feature_1_desc: "Plain-language guidance for the next 48 hours, tailored to each plant in your collection.",
    landing_feature_2_title: "Living plant journal",
    landing_feature_2_desc: "Track watering, light, pots, and replants. Spot trends before they become problems.",
    landing_feature_3_title: "Neighborhood marketplace",
    landing_feature_3_desc: "Trade seeds, cuttings, and tools with growers within walking distance.",
    landing_feature_4_title: "Bilingual by design",
    landing_feature_4_desc: "Native English and Persian (with proper RTL) so every gardener feels at home.",
    landing_how_eyebrow: "How it works",
    landing_how_title: "From sign-up to first sprout in three steps",
    landing_step_1_title: "Create your account",
    landing_step_1_desc: "60 seconds, no credit card required.",
    landing_step_2_title: "Add your plants",
    landing_step_2_desc: "Tell jaliz what you grow, where, and how much sun it gets.",
    landing_step_3_title: "Get daily advice",
    landing_step_3_desc: "Open the dashboard and act on the next-best step.",
    landing_final_cta_title: "Ready to grow with jaliz?",
    landing_final_cta_subtitle: "Join the gardeners turning weather data into healthier plants.",
    landing_final_cta_button: "Get started — it's free",
    landing_footer: "Made with care for gardeners everywhere.",
    // Marketplace
    mp_title: "Marketplace",
    mp_subtitle: "Sell, swap or share seeds, cuttings, tools and produce with growers nearby.",
    mp_post_btn: "Post a listing",
    mp_view_all: "View all",
    mp_tab_all: "All",
    mp_tab_seed: "Seeds",
    mp_tab_cutting: "Cuttings",
    mp_tab_tool: "Tools",
    mp_tab_produce: "Produce",
    mp_tab_mine: "My listings",
    mp_search_ph: "Search listings…",
    mp_no_results: "No listings match your filters.",
    mp_empty_title: "The marketplace is quiet… for now",
    mp_empty_desc: "Be the first to share a seed, cutting, tool or harvest with your neighbors.",
    mp_dashboard_empty_title: "No listings nearby yet",
    mp_dashboard_empty_desc: "Be the first to post one.",
    mp_completed_badge: "Done",
    mp_type_seed: "Seed",
    mp_type_cutting: "Cutting",
    mp_type_tool: "Tool",
    mp_type_produce: "Produce",
    mp_mode_sell: "For sale",
    mp_mode_exchange: "Trade",
    mp_mode_free: "Free",
    mp_view_details: "View details",
    // Form
    mp_form_create_title: "Post a new listing",
    mp_form_edit_title: "Edit listing",
    mp_field_type: "Category",
    mp_field_mode: "Listing type",
    mp_field_title_label: "Title",
    mp_field_title_ph: "e.g., Heirloom tomato seeds",
    mp_field_description_label: "Description",
    mp_field_description_ph: "Quantity, condition, growing notes…",
    mp_field_image_label: "Photo (optional)",
    mp_field_price_label: "Price (toman)",
    mp_field_price_ph: "e.g., 50000",
    mp_field_exchange_for_label: "Looking to trade for",
    mp_field_exchange_for_ph: "e.g., basil seeds, herb cuttings",
    mp_field_location_label: "Location (optional)",
    mp_field_location_ph: "e.g., Tehran, district 5",
    mp_field_phone_label: "Contact phone (optional)",
    mp_field_phone_ph: "e.g., 0912XXXXXXX",
    mp_field_phone_hint: "Saved to your profile and shown on this listing for calls and WhatsApp.",
    mp_form_submit_create: "Publish listing",
    mp_form_submit_save: "Save changes",
    mp_form_error_required: "Please fill in title and description.",
    mp_form_error_price: "Please enter a valid price.",
    mp_form_error_generic: "Couldn't save the listing. Please try again.",
    // Details
    mp_details_owner: "Posted by",
    mp_details_posted_at: "Posted",
    mp_details_completed_at: "Completed",
    mp_details_no_phone: "No phone provided",
    mp_action_complete: "Mark as done",
    mp_action_reopen: "Reopen listing",
    mp_action_edit: "Edit",
    mp_action_delete: "Delete",
    mp_action_message: "Message",
    mp_action_call: "Call",
    mp_action_whatsapp: "WhatsApp",
    mp_action_sign_in_to_contact: "Sign in to contact the seller",
    mp_confirm_delete: "Delete this listing? This cannot be undone.",
    mp_status_active: "Active",
    mp_status_completed: "Completed",
    // Chat
    mp_chat_title: "Conversation",
    mp_chat_no_messages: "Say hello — your message starts the conversation.",
    mp_chat_send: "Send",
    mp_chat_input_ph: "Write a message…",
    mp_chat_sign_in_required: "Sign in to send messages."
  },
  fa: {
    app_title: "جالیز",
    dashboard: "داشبورد",
    marketplace: "بازارچه",
    my_plants: "گیاهان من",
    welcome_title: "صبح بخیر، سارا! 🪴",
    morning_greeting: "صبح بخیر، سارا! 🪴",
    afternoon_greeting: "ظهر بخیر، سارا! 🪴",
    evening_greeting: "عصر بخیر، سارا! 🪴",
    night_greeting: "شب بخیر، سارا! 🪴",
    welcome_desc: "امروز باغچه شما به این موارد نیاز دارد.",
    watering_title: "برنامه آبیاری",
    watering_desc: "۳ گیاه امروز به آب نیاز دارند.",
    weather_title: "مشاوره هواشناسی محلی",
    weather_desc: "مشاوره هوشمند باغبانی بر اساس گیاهان شما و پیش‌بینی ۴۸ ساعته.",
    analyzing: "در حال بررسی ریسک‌های آب و هوایی...",
    generate_btn: "دریافت مشاوره",
    generating_btn: "در حال پردازش...",
    advice_prompt: "برای دریافت مشاوره اختصاصی برای گیاهان خود، روی دکمه زیر کلیک کنید.",
    market_title: "بازارچه اطراف شما",
    market_within: "شعاع ۵ کیلومتری",
    contact_btn: "تماس در واتساپ",
    away: "فاصله",
    by: "توسط",
    add_plant: "افزودن گیاه",
    add_new_plant: "افزودن گیاه جدید",
    plant_name: "نام گیاه",
    plant_name_ph: "مثال: برگ انجیری (مونسترا)",
    plant_type: "نوع گیاه",
    plant_type_ph: "مثال: آپارتمانی استوایی",
    location_type: "مکان قرارگیری",
    location_indoor: "فضای داخلی (Indoor)",
    location_outdoor: "فضای باز (Outdoor)",
    light_exposure: "میزان نور",
    light_low: "نور کم",
    light_partial: "سایه جزئی",
    light_bright: "نور غیرمستقیم و روشن",
    light_full: "آفتاب کامل",
    pot_type: "نوع گلدان",
    pot_terracotta: "سفالی",
    pot_plastic: "پلاستیکی",
    pot_ceramic: "سرامیکی",
    pot_metal: "فلزی",
    pot_other: "سایر",
    has_drainage: "دارای سوراخ زهکشی",
    last_watered: "آخرین آبیاری",
    recently_replanted: "اخیراً تعویض گلدان شده",
    plant_image: "تصویر گیاه (اختیاری)",
    health_status: "وضعیت سلامت",
    health_excellent: "عالی",
    health_good: "خوب",
    health_needs_attention: "نیاز به توجه",
    cancel: "انصراف",
    save: "ذخیره گیاه",
    no_plants: "هنوز هیچ گیاهی اضافه نکرده‌اید.",
    watered_today: "امروز آبیاری شده",
    watered_days_ago: "روز پیش",
    care_tips: "نکات مراقبتی",
    care_tips_ph: "نکات کلی نگهداری...",
    watering_tips: "نکات آبیاری",
    watering_tips_ph: "زمان‌بندی و نکات آبیاری...",
    settings: "تنظیمات",
    api_key_title: "تنظیمات کلید API جمینای",
    api_key_desc: "کلید API جمینای خود را وارد کنید تا مشاوره هوشمند فعال شود.",
    api_key_label: "کلید API",
    api_key_ph: "AIzaSy...",
    fetch_models: "دریافت لیست مدل‌ها",
    fetching: "در حال دریافت...",
    select_model: "انتخاب مدل",
    token_limit: "محدودیت توکن",
    input_tokens: "ورودی",
    output_tokens: "خروجی",
    save_settings: "ذخیره تنظیمات",
    saved_successfully: "تنظیمات با موفقیت ذخیره شد!",
    api_key_required: "وارد کردن کلید API برای دریافت مشاوره الزامی است.",
    user_location_title: "موقعیت مکانی شما",
    user_location_label: "شهر، کشور",
    user_location_ph: "مثال: تهران، ایران",
    // Auth
    sign_in: "ورود",
    sign_up: "ثبت‌نام",
    sign_out: "خروج",
    account: "حساب کاربری",
    admin_panel: "پنل مدیریت",
    login_title: "خوش برگشتید",
    login_desc: "به حساب کاربری جالیز خود وارد شوید.",
    register_title: "ساخت حساب کاربری",
    register_desc: "به جالیز بپیوندید و باغبانی هوشمندتر را شروع کنید.",
    email: "ایمیل",
    email_ph: "you@example.com",
    password: "رمز عبور",
    password_ph: "حداقل ۶ کاراکتر",
    confirm_password: "تکرار رمز عبور",
    full_name: "نام و نام خانوادگی",
    full_name_ph: "نام کامل شما",
    register_btn: "ساخت حساب",
    login_btn: "ورود",
    no_account: "حساب کاربری ندارید؟",
    have_account: "قبلاً ثبت‌نام کرده‌اید؟",
    auth_error_invalid_credentials: "ایمیل یا رمز عبور اشتباه است.",
    auth_error_email_exists: "حسابی با این ایمیل قبلاً ثبت شده است.",
    auth_error_user_inactive: "این حساب کاربری غیرفعال شده است.",
    auth_error_user_not_found: "کاربر یافت نشد.",
    auth_error_weak_password: "رمز عبور باید حداقل ۶ کاراکتر باشد.",
    auth_error_invalid_email: "لطفاً یک ایمیل معتبر وارد کنید.",
    auth_error_empty_field: "لطفاً همه فیلدهای ضروری را پر کنید.",
    auth_error_password_mismatch: "رمز عبور و تکرار آن یکسان نیستند.",
    auth_error_generic: "خطایی رخ داد. لطفاً دوباره تلاش کنید.",

    // Admin panel
    admin_title: "مدیریت کاربران",
    admin_desc: "کاربران ثبت‌شده، نقش‌ها و دسترسی‌ها را مدیریت کنید.",
    admin_search_ph: "جستجو بر اساس نام یا ایمیل…",
    admin_total_users: "کل کاربران",
    admin_active_users: "فعال",
    admin_admins: "ادمین‌ها",
    admin_col_user: "کاربر",
    admin_col_role: "نقش",
    admin_col_status: "وضعیت",
    admin_col_joined: "تاریخ عضویت",
    admin_col_actions: "عملیات",
    admin_role_admin: "ادمین",
    admin_role_user: "کاربر",
    admin_status_active: "فعال",
    admin_status_inactive: "غیرفعال",
    admin_action_reset: "بازنشانی رمز",
    admin_action_delete: "حذف",
    admin_action_deactivate: "غیرفعال کردن",
    admin_action_activate: "فعال کردن",
    admin_no_users: "کاربری مطابق با جستجو یافت نشد.",
    admin_confirm_delete: "این کاربر برای همیشه حذف شود؟ این عمل قابل بازگشت نیست.",
    admin_reset_title: "بازنشانی رمز عبور",
    admin_reset_desc: "یک رمز عبور جدید برای {name} تعیین کنید. در ورود بعدی باید از آن استفاده کند.",
    admin_reset_new_password: "رمز عبور جدید",
    admin_reset_btn: "ثبت رمز",
    admin_reset_success: "رمز عبور با موفقیت تغییر کرد.",
    admin_self_warning: "نمی‌توانید نقش یا وضعیت حساب خودتان را از اینجا تغییر دهید.",
    admin_only: "این صفحه فقط مخصوص ادمین‌هاست.",
    go_home: "بازگشت به داشبورد",
    auth_required: "برای ادامه لطفاً وارد شوید.",
    you_label: "(شما)",
    // Admin AI API config
    admin_ai_title: "تنظیمات API هوش مصنوعی",
    admin_ai_desc: "کلید API جمینای را وارد کنید تا همه کاربران بتوانند از قابلیت‌های AI استفاده کنند.",
    admin_ai_key_label: "کلید API جمینای",
    admin_ai_key_ph: "AIzaSy...",
    admin_ai_fetch_models: "تایید و دریافت مدل‌ها",
    admin_ai_select_model: "مدل پیش‌فرض",
    admin_ai_save: "ذخیره تنظیمات AI",
    admin_ai_saved: "تنظیمات AI برای همه کاربران ذخیره شد!",
    admin_ai_no_key: "هنوز کلید API تنظیم نشده است.",
    // Landing page
    landing_hero_eyebrow: "باغبانی هوشمند با دقت محلی",
    landing_hero_title: "گیاهان شادتر، در هر فصل.",
    landing_hero_subtitle: "جالیز هواشناسی محله شما را می‌خواند، گیاهان‌تان را می‌شناسد و دقیقاً می‌گوید امروز چه کنید — به فارسی یا انگلیسی.",
    landing_cta_primary: "ساخت حساب رایگان",
    landing_cta_secondary: "ورود",
    landing_hero_card_title: "مشاوره امروز",
    landing_hero_card_line1: "امشب جبههٔ سرد می‌رسد — مونسترا را از کنار پنجره دور کن.",
    landing_hero_card_line2: "گوجه به آفتاب کامل می‌رود: صبح زود و عمیق آبیاری کن.",
    landing_hero_card_badge: "ساخته‌شده با AI",
    landing_trust_label: "مورد اعتماد باغبان‌هایی که پرورش می‌دهند:",
    landing_trust_chip_1: "گیاهان استوایی",
    landing_trust_chip_2: "سبزیجات",
    landing_trust_chip_3: "گیاهان دارویی",
    landing_trust_chip_4: "ساکولنت‌ها",
    landing_features_eyebrow: "چرا جالیز",
    landing_features_title: "هر چه یک باغبان پرمشغله نیاز دارد",
    landing_features_subtitle: "یک همراه آرام که داده‌های هواشناسی، زیست‌شناسی گیاه و محلهٔ شما را به قدم‌های روشن بعدی تبدیل می‌کند.",
    landing_feature_1_title: "مشاوره هوشمند آب و هوا",
    landing_feature_1_desc: "راهنمای ساده برای ۴۸ ساعت پیش رو، متناسب با هر گیاهی که داری.",
    landing_feature_2_title: "دفتر زندهٔ گیاهان",
    landing_feature_2_desc: "آبیاری، نور، گلدان و تعویض گلدان را ثبت کن. مشکل‌ها را قبل از بدتر شدن ببین.",
    landing_feature_3_title: "بازارچهٔ محله",
    landing_feature_3_desc: "بذر، قلمه و ابزار را با باغبان‌های فاصلهٔ پیاده‌روی تبادل کن.",
    landing_feature_4_title: "دو زبانه از پایه",
    landing_feature_4_desc: "فارسی و انگلیسی، با پشتیبانی کامل RTL — هر باغبانی احساس راحتی می‌کند.",
    landing_how_eyebrow: "چطور کار می‌کند",
    landing_how_title: "از ثبت‌نام تا اولین جوانه، در سه قدم",
    landing_step_1_title: "حساب کاربری بساز",
    landing_step_1_desc: "۶۰ ثانیه، بدون نیاز به کارت اعتباری.",
    landing_step_2_title: "گیاهانت را اضافه کن",
    landing_step_2_desc: "به جالیز بگو چه می‌کاری، کجا، و چقدر نور می‌گیرد.",
    landing_step_3_title: "مشاورهٔ روزانه بگیر",
    landing_step_3_desc: "داشبورد را باز کن و بهترین قدم بعدی را بردار.",
    landing_final_cta_title: "آماده‌ای با جالیز رشد کنی؟",
    landing_final_cta_subtitle: "به باغبان‌هایی بپیوند که داده‌های هواشناسی را به گیاهان سالم‌تر تبدیل می‌کنند.",
    landing_final_cta_button: "همین حالا شروع کن — رایگان است",
    landing_footer: "ساخته‌شده با عشق برای باغبان‌ها.",
    // Marketplace
    mp_title: "بازارچه",
    mp_subtitle: "بذر، قلمه، ابزار و محصولات را با باغبان‌های نزدیک بفروش، تبادل کن یا هدیه بده.",
    mp_post_btn: "ثبت آگهی",
    mp_view_all: "مشاهده همه",
    mp_tab_all: "همه",
    mp_tab_seed: "بذر",
    mp_tab_cutting: "قلمه",
    mp_tab_tool: "ابزار",
    mp_tab_produce: "محصولات",
    mp_tab_mine: "آگهی‌های من",
    mp_search_ph: "جستجو در آگهی‌ها…",
    mp_no_results: "آگهی‌ای با فیلتر فعلی پیدا نشد.",
    mp_empty_title: "بازارچه فعلاً خلوت است",
    mp_empty_desc: "اولین نفری باش که بذر، قلمه، ابزار یا محصول را با همسایه‌هایش به اشتراک می‌گذارد.",
    mp_dashboard_empty_title: "هنوز آگهی‌ای در نزدیکی نیست",
    mp_dashboard_empty_desc: "اولین آگهی را تو ثبت کن.",
    mp_completed_badge: "انجام شد",
    mp_type_seed: "بذر",
    mp_type_cutting: "قلمه",
    mp_type_tool: "ابزار",
    mp_type_produce: "محصول",
    mp_mode_sell: "فروش",
    mp_mode_exchange: "تبادل",
    mp_mode_free: "رایگان",
    mp_view_details: "مشاهده جزئیات",
    // Form
    mp_form_create_title: "ثبت آگهی جدید",
    mp_form_edit_title: "ویرایش آگهی",
    mp_field_type: "دسته‌بندی",
    mp_field_mode: "نوع آگهی",
    mp_field_title_label: "عنوان",
    mp_field_title_ph: "مثلاً: بذر گوجه فرنگی ارگانیک",
    mp_field_description_label: "توضیحات",
    mp_field_description_ph: "تعداد، وضعیت، نکات کاشت…",
    mp_field_image_label: "تصویر (اختیاری)",
    mp_field_price_label: "قیمت (تومان)",
    mp_field_price_ph: "مثلاً: ۵۰۰۰۰",
    mp_field_exchange_for_label: "در ازای",
    mp_field_exchange_for_ph: "مثلاً: بذر ریحان، قلمه گیاه دارویی",
    mp_field_location_label: "محل (اختیاری)",
    mp_field_location_ph: "مثلاً: تهران، منطقه ۵",
    mp_field_phone_label: "شماره تماس (اختیاری)",
    mp_field_phone_ph: "مثلاً: ۰۹۱۲۰۰۰۰۰۰۰",
    mp_field_phone_hint: "در پروفایلت ذخیره می‌شود و برای تماس و واتساپ روی این آگهی نمایش داده می‌شود.",
    mp_form_submit_create: "انتشار آگهی",
    mp_form_submit_save: "ذخیره تغییرات",
    mp_form_error_required: "لطفاً عنوان و توضیحات را وارد کن.",
    mp_form_error_price: "لطفاً یک قیمت معتبر وارد کن.",
    mp_form_error_generic: "ذخیره آگهی ممکن نشد. دوباره تلاش کن.",
    // Details
    mp_details_owner: "ثبت‌کننده",
    mp_details_posted_at: "تاریخ ثبت",
    mp_details_completed_at: "تاریخ تکمیل",
    mp_details_no_phone: "شماره تماسی ثبت نشده",
    mp_action_complete: "علامت‌گذاری به‌عنوان انجام‌شده",
    mp_action_reopen: "بازگشایی آگهی",
    mp_action_edit: "ویرایش",
    mp_action_delete: "حذف",
    mp_action_message: "پیام",
    mp_action_call: "تماس",
    mp_action_whatsapp: "واتساپ",
    mp_action_sign_in_to_contact: "برای تماس با فروشنده وارد شو",
    mp_confirm_delete: "این آگهی حذف شود؟ این عمل قابل بازگشت نیست.",
    mp_status_active: "فعال",
    mp_status_completed: "تکمیل‌شده",
    // Chat
    mp_chat_title: "گفتگو",
    mp_chat_no_messages: "سلام کن — اولین پیام تو گفتگو را شروع می‌کند.",
    mp_chat_send: "ارسال",
    mp_chat_input_ph: "پیام خود را بنویسید…",
    mp_chat_sign_in_required: "برای ارسال پیام وارد شو."
  }
}

type TranslationKey = keyof typeof translations.en

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Read from localStorage if available
    const saved = localStorage.getItem("jaliz-lang") as Language
    if (saved && (saved === "en" || saved === "fa")) {
      setLanguage(saved)
    }
  }, [])

  useEffect(() => {
    // Save preference and update document direction
    localStorage.setItem("jaliz-lang", language)
    document.documentElement.dir = language === "fa" ? "rtl" : "ltr"
    document.documentElement.lang = language
    
    if (language === "fa") {
      document.body.style.fontFamily = "var(--font-vazirmatn), ui-sans-serif, system-ui, sans-serif"
      document.documentElement.style.setProperty("--font-sans", "var(--font-vazirmatn)")
    } else {
      document.body.style.fontFamily = ""
      document.documentElement.style.setProperty("--font-sans", "var(--font-geist-sans)")
    }
  }, [language])

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key]
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
