"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

export type Language = "en" | "fa"

const translations = {
  en: {
    app_title: "jaliz",
    home: "Home",
    schedule: "Schedule & Care",
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    my_plants: "My Plants",
    nav_my_plants: "Plants",
    nav_schedule: "Care",
    nav_marketplace: "Market",
    nav_chats: "Chats",
    nav_smart_detect: "Detect",
    welcome_title: "Good morning, Sarah! 🪴",
    morning_greeting: "Good morning, Sarah! 🪴",
    afternoon_greeting: "Good afternoon, Sarah! 🪴",
    evening_greeting: "Good evening, Sarah! 🪴",
    night_greeting: "Good night, Sarah! 🪴",
    welcome_desc: "Here's what your garden needs today.",
    watering_title: "Watering Schedule",
    watering_desc: "3 plants need water today.",
    weather_title: "Hyper-Local Weather Advice",
    weather_desc: "AI-powered gardening advice based on your plants and local 48h forecast.",
    analyzing: "Analyzing weather risks...",
    generate_btn: "Generate Advice",
    generating_btn: "Generating...",
    advice_prompt: "Click below to generate actionable advice for your Monstera and Tomato plants.",
    market_title: "Nearby Marketplace",
    market_within: "Within 5km",
    contact_btn: "Contact via WhatsApp",
    away: "away",
    by: "by",
    add_plant: "Add Plant",
    add_new_plant: "Add a New Plant",
    plant_name: "Plant Name",
    plant_name_ph: "e.g., Monstera Deliciosa",
    plant_type: "Plant Type",
    plant_type_ph: "e.g., Indoor Tropical",
    location_type: "Location",
    location_indoor: "Indoor",
    location_outdoor: "Outdoor",
    light_exposure: "Light Exposure",
    light_low: "Low Light",
    light_partial: "Partial Shade",
    light_bright: "Bright Indirect",
    light_full: "Full Sun",
    pot_type: "Pot Type",
    pot_terracotta: "Terracotta",
    pot_plastic: "Plastic",
    pot_ceramic: "Ceramic",
    pot_metal: "Metal",
    pot_other: "Other",
    growing_medium: "Growing Medium",
    medium_soil: "Soil",
    medium_water: "Water (Hydroponic)",
    has_drainage: "Has Drainage Hole",
    last_watered: "Last Watered",
    last_soil_change: "Last Soil Change",
    relative_date_today: "Today",
    relative_date_3days: "3 days ago",
    relative_date_week: "Last week",
    watering_interval_label: "Watering Interval",
    watering_interval_days: "days",
    watering_interval_locked_hint: "Suggested watering interval",
    soil_change_recommendation: "Soil Change Advice",
    soil_change_unknown: "Not recorded",
    soil_change_months_ago: "months ago",
    recently_replanted: "Recently Replanted",
    plant_image: "Plant Image (Optional)",
    health_status: "Health Status",
    health_excellent: "Excellent",
    health_good: "Good",
    health_needs_attention: "Needs Attention",
    cancel: "Cancel",
    save: "Save Plant",
    no_plants_title: "Your garden is empty",
    no_plants_desc: "You haven't added any plants yet. Let's bring some green into your space!",
    no_plants_cta: "Add Your First Plant",
    watered_today: "Watered today",
    watered_days_ago: "days ago",
    share_plant: "Share",
    share_plant_cta: "Share your plant",
    share_plant_desc: "Post a cute update with photo, status & next care — perfect for social media!",
    share_plant_preparing: "Creating share card…",
    share_plant_success: "Ready to post! Caption copied & image saved.",
    share_plant_cancelled: "Share cancelled",
    care_tips: "Care Tips",
    care_tips_ph: "General care tips...",
    watering_tips: "Watering Tips",
    watering_tips_ph: "Watering schedule and tips...",
    settings: "Settings",
    changelog: "Changelog",
    api_key_title: "Gemini API Settings",
    api_key_desc: "Enter your Gemini API key to power the AI gardening advice.",
    api_key_label: "API Key",
    api_key_ph: "AIzaSy...",
    fetch_models: "Fetch Models",
    fetching: "Fetching...",
    select_model: "Select a Model",
    token_limit: "Token Limit",
    input_tokens: "Input",
    output_tokens: "Output",
    save_settings: "Save Settings",
    saved_successfully: "Settings saved successfully!",
    theme_label: "Theme",
    theme_desc: "Choose light or dark appearance for the app.",
    theme_light: "Light",
    theme_dark: "Dark",
    api_key_required: "API Key is required to generate advice.",
    user_location_title: "Your Location",
    user_location_label: "City, Country",
    user_location_ph: "e.g. Tehran, Iran",
    // Auth
    sign_in: "Sign in",
    sign_up: "Sign up",
    sign_out: "Sign out",
    account: "Account",
    admin_panel: "Admin",
    chats: "Chats",
    login_title: "Welcome back",
    login_desc: "Sign in to your jaliz account.",
    register_title: "Create your account",
    register_desc: "Enter your email and verify with a one-time code.",
    email: "Email",
    email_ph: "you@example.com",
    password: "Password",
    password_ph: "At least 6 characters",
    confirm_password: "Confirm password",
    full_name: "Full name",
    full_name_ph: "Your full name",
    settings_set_password: "Set a password",
    settings_set_password_desc: "Optional. After setting a password you can also sign in with email and password.",
    register_btn: "Create account",
    login_btn: "Sign in",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",
    login_with_password: "Login with Password",
    login_with_otp: "Login with OTP",
    send_otp: "Send Verification Code",
    sending_otp: "Sending Code...",
    otp_sent_success: "Verification code sent to your email.",
    otp_code: "Verification Code (OTP)",
    otp_ph: "Enter 6-digit code",
    change_email: "Change Email",
    login_btn_otp: "Verify & Sign In",
    auth_error_invalid_credentials: "Email, password, or verification code is incorrect.",
    auth_error_email_exists: "An account with this email already exists.",
    auth_error_user_inactive: "This account has been disabled.",
    auth_error_user_not_found: "User not found.",
    auth_error_weak_password: "Password must be at least 6 characters.",
    auth_error_invalid_email: "Please enter a valid email address.",
    auth_error_empty_field: "Please fill in all required fields.",
    auth_error_password_mismatch: "Passwords do not match.",
    auth_error_otp_send_failed:
      "Could not send the verification email. Check your email address or try password login.",
    auth_error_generic: "Something went wrong. Please try again.",
    promo_top_text: "🎁 Get 200,000 Tomans first purchase discount! Sign up now to claim your gift.",
    promo_top_cta: "Sign Up & Claim",
    promo_card_title: "200,000 Tomans First Purchase Gift!",
    promo_card_desc: "New to Jaliz? Sign up today and get 200,000 Tomans off your first order in our marketplace.",
    promo_card_cta: "Register & Claim Offer",

    // Admin panel
    admin_title: "User Management",
    admin_desc: "Manage registered users, roles and access.",
    admin_search_ph: "Search by name or email…",
    admin_total_users: "Total users",
    admin_active_users: "Active",
    admin_admins: "Admins",
    admin_col_user: "User",
    admin_col_role: "Role",
    admin_col_status: "Status",
    admin_col_joined: "Joined",
    admin_col_actions: "Actions",
    admin_role_admin: "Admin",
    admin_role_user: "User",
    admin_status_active: "Active",
    admin_status_inactive: "Disabled",
    admin_create_user_btn: "Create user",
    admin_action_edit: "Edit",
    admin_action_reset: "Reset password",
    admin_action_delete: "Delete",
    admin_action_deactivate: "Disable",
    admin_action_activate: "Enable",
    admin_no_users: "No users match your search.",
    admin_confirm_delete: "Delete this user permanently? This cannot be undone.",
    admin_create_title: "Create user",
    admin_create_desc: "Set the user's name, email and password. They can sign in with this password immediately.",
    admin_edit_title: "Edit user",
    admin_edit_desc: "Update the user's name, email, role or password.",
    admin_save_user: "Save user",
    admin_password_optional: "Leave blank to keep current password",
    admin_user_active: "User is active",
    admin_create_success: "User created.",
    admin_update_success: "User updated.",
    admin_reset_title: "Reset password",
    admin_reset_desc: "Set a new password for {name}. They will need to use it on their next sign-in.",
    admin_reset_new_password: "New password",
    admin_reset_btn: "Set password",
    admin_reset_success: "Password updated.",
    admin_self_warning: "You can't change the role or disable your own account here.",
    admin_only: "This page is for administrators only.",
    go_home: "Go to dashboard",
    auth_required: "Please sign in to continue.",
    you_label: "(you)",
    // Admin AI API config
    admin_ai_title: "AI API Configuration",
    admin_ai_desc: "Configure the AI provider and API key used by all users.",
    admin_ai_provider_label: "AI Provider",
    admin_ai_provider_sotoon: "Sotoon Intelligence",
    admin_ai_provider_gemini_hint: "Uses Google's Gemini models. Requires a Google AI API key.",
    admin_ai_provider_sotoon_hint: "Iranian AI service (OpenAI-compatible). No filtering issues.",
    admin_ai_provider_gapgpt: "GapGPT",
    admin_ai_provider_gapgpt_hint: "Iranian AI gateway (OpenAI-compatible). Access to GPT, Gemini, and more models.",
    admin_ai_key_label: "API Key",
    admin_ai_key_ph: "AIzaSy...",
    admin_ai_key_ph_sotoon: "sk-...",
    admin_ai_key_ph_gapgpt: "gapgpt-...",
    admin_ai_fetch_models: "Verify & Fetch Models",
    admin_ai_select_model: "Default Model",
    admin_ai_save: "Save AI Settings",
    admin_ai_saved: "AI settings saved for all users!",
    admin_ai_no_key: "No API key configured yet.",
    // Landing page
    landing_hero_eyebrow: "Your Friendly Plant Assistant",
    landing_hero_title: "Never kill a plant again.",
    landing_hero_subtitle: "jaliz tells you exactly when to water and how to care for your plants, step by step.",
    landing_cta_primary: "Create your free account",
    landing_cta_secondary: "Sign in",
    landing_hero_card_title: "Today's easy tip",
    landing_hero_card_line1: "Your Monstera is looking thirsty! Give it a good watering today.",
    landing_hero_card_line2: "Move your Aloe Vera a bit closer to the window for more light.",
    landing_hero_card_badge: "Simple Advice",
    landing_trust_label: "Perfect for your first",
    landing_trust_chip_1: "Houseplants",
    landing_trust_chip_2: "Succulents",
    landing_trust_chip_3: "Balcony Flowers",
    landing_trust_chip_4: "Herbs",
    landing_features_eyebrow: "Why jaliz",
    landing_features_title: "Plant care made incredibly easy",
    landing_features_subtitle: "No green thumb required. We guide you through everything you need to keep your plants thriving.",
    landing_feature_1_title: "Simple Care Reminders",
    landing_feature_1_desc: "No confusing jargon. Just easy, timely reminders for watering, sunlight, and basic care.",
    landing_feature_2_title: "Track Your Progress",
    landing_feature_2_desc: "Never forget when you last watered. Keep a simple, fun diary of your plant's journey.",
    landing_feature_3_title: "Meet Plant Lovers",
    landing_feature_3_desc: "Connect with friendly neighbors to share beginner tips, cuttings, and easy-to-grow plants.",
    landing_feature_4_title: "Easy & Bilingual",
    landing_feature_4_desc: "Designed for everyone, with simple, friendly language in both English and Persian.",
    landing_how_eyebrow: "How it works",
    landing_how_title: "Get started in 3 easy steps",
    landing_step_1_title: "Create an account",
    landing_step_1_desc: "Takes just 1 minute. It's completely free.",
    landing_step_2_title: "Add your plants",
    landing_step_2_desc: "Snap a photo or type the name, and we'll figure out the rest.",
    landing_step_3_title: "Follow simple tips",
    landing_step_3_desc: "Just check your easy daily checklist to keep your plants happy.",
    landing_final_cta_title: "Check your plant in seconds",
    landing_final_cta_subtitle: "Start with smart diagnosis — then create an account if you want to save your plant and get reminders.",
    landing_final_cta_button: "Get started — it's free",
    landing_footer: "Made with love for beginners everywhere.",
    landing_slide_diag_title: "Smart plant diagnosis",
    landing_slide_diag_desc: "Snap a photo and Jaliz spots stress, pests, and disease — then gives clear care steps.",
    landing_cta_diagnose: "Start smart diagnosis",
    landing_cta_register_plant: "Sign up & register your plant",
    landing_cta_login_hint: "Already have an account? Sign in",
    landing_cta_footer_note: "Diagnosis works right away. Sign up only when you want to save a plant.",
    landing_skip: "Skip",
    landing_next: "Next",
    landing_prev: "Previous",
    smart_diag_guest_save_hint: "Create a free account to save this plant to your garden.",
    smart_diag_opt_new_guest: "Sign up & save this plant",
    blog: "Blog",
    articles: "Articles",
    // Marketplace
    mp_title: "Marketplace",
    mp_subtitle: "Sell, swap or share seeds, cuttings, tools and produce with growers nearby.",
    mp_post_btn: "Post a listing",
    mp_view_all: "View all",
    mp_tab_all: "All",
    mp_tab_seed: "Seeds",
    mp_tab_cutting: "Cuttings",
    mp_tab_tool: "Tools",
    mp_tab_produce: "Produce",
    mp_tab_mine: "My listings",
    mp_search_ph: "Search listings…",
    mp_no_results: "No listings match your filters.",
    mp_empty_title: "The marketplace is quiet… for now",
    mp_empty_desc: "Be the first to share a seed, cutting, tool or harvest with your neighbors.",
    mp_dashboard_empty_title: "No listings nearby yet",
    mp_dashboard_empty_desc: "Be the first to post one.",
    mp_completed_badge: "Done",
    mp_type_seed: "Seed",
    mp_type_cutting: "Cutting",
    mp_type_tool: "Tool",
    mp_type_produce: "Produce",
    mp_mode_sell: "For sale",
    mp_mode_exchange: "Trade",
    mp_mode_free: "Free",
    mp_view_details: "View details",
    mp_advice_recs_title: "Suggested from marketplace",
    mp_advice_recs_view: "View in marketplace",
    // Form
    mp_form_create_title: "Post a new listing",
    mp_form_edit_title: "Edit listing",
    mp_field_type: "Category",
    mp_field_mode: "Listing type",
    mp_field_title_label: "Title",
    mp_field_title_ph: "e.g., Heirloom tomato seeds",
    mp_field_description_label: "Description",
    mp_field_description_ph: "Quantity, condition, growing notes…",
    mp_field_image_label: "Photo (optional)",
    mp_field_price_label: "Price (toman)",
    mp_field_price_ph: "e.g., 50000",
    mp_field_exchange_for_label: "Looking to trade for",
    mp_field_exchange_for_ph: "e.g., basil seeds, herb cuttings",
    mp_field_location_label: "Location (optional)",
    mp_field_location_ph: "e.g., Tehran, district 5",
    mp_field_phone_label: "Contact phone (optional)",
    mp_field_phone_ph: "e.g., 0912XXXXXXX",
    mp_field_phone_hint: "Saved to your profile and shown on this listing for calls and WhatsApp.",
    mp_form_submit_create: "Publish listing",
    mp_form_submit_save: "Save changes",
    mp_form_error_required: "Please fill in title and description.",
    mp_form_error_price: "Please enter a valid price.",
    mp_form_error_generic: "Couldn't save the listing. Please try again.",
    // Details
    mp_details_owner: "Posted by",
    mp_details_posted_at: "Posted",
    mp_details_completed_at: "Completed",
    mp_details_no_phone: "No phone provided",
    mp_action_complete: "Mark as done",
    mp_action_reopen: "Reopen listing",
    mp_action_edit: "Edit",
    mp_action_delete: "Delete",
    mp_action_message: "Message",
    mp_action_call: "Call",
    mp_action_whatsapp: "WhatsApp",
    mp_action_sign_in_to_contact: "Sign in to contact the seller",
    mp_confirm_delete: "Delete this listing? This cannot be undone.",
    mp_status_active: "Active",
    mp_status_completed: "Completed",
    // Chat
    mp_chat_title: "Conversation",
    mp_chat_no_messages: "Say hello — your message starts the conversation.",
    mp_chat_send: "Send",
    mp_chat_input_ph: "Write a message…",
    mp_chat_sign_in_required: "Sign in to send messages.",
    // Smart detect
    smart_detect: "Smart Detect",
    smart_diag_title: "Smart Diagnosis",
    smart_diag_desc: "Analyze your plant's health using AI to detect issues and get care solutions.",
    smart_diag_btn: "Start Diagnosis",
    smart_diag_loading: "Analyzing health issues...",
    smart_diag_result_title: "AI Diagnosis Report",
    smart_diag_health: "Diagnosed Health",
    smart_diag_issue: "AI Diagnosis Summary",
    smart_diag_advice: "Treatment & Care Advice",
    smart_diag_opt_new: "Register as a New Pot",
    smart_diag_opt_existing: "Log Status for an Existing Pot",
    smart_diag_opt_discard: "Discard Analysis",
    smart_diag_select_plant: "Select plant to log status",
    smart_diag_save_success: "Status logged successfully!",
    smart_diag_new_success: "Plant registered successfully!",
    smart_diag_select_placeholder: "Choose a plant...",
    smart_diag_save_log_btn: "Save Status Log",
    // Profile Edit
    edit_profile: "Edit Profile",
    profile_photo: "Profile Photo",
    phone_number: "Phone Number",
    phone_number_ph: "e.g., 0912XXXXXXX",
    profile_update_success: "Profile updated successfully!",
    change_photo: "Change Photo",
    remove_photo: "Remove Photo",
    // Install Prompt
    install_title: "Install Jaliz App",
    install_description: "Add Jaliz to your home screen for quick access, offline support, and a better experience.",
    install_button: "Install App",
    install_ios_guide: "Add Jaliz to your home screen in two simple steps:",
    install_ios_step1: "Share",
    install_ios_step2: "Add to Home",
    // Storefront Scan
    store_scan_welcome: "Welcome to {store}! 🪴",
    store_scan_welcome_default: "Welcome to our partner store! 🪴",
    store_scan_subtitle: "Take a picture of any plant to learn how to care for it!",
    store_scan_take_photo: "Take Photo or Upload Image",
    store_scan_analyzing: "Analyzing plant details...",
    store_scan_pwa_title: "Never forget to water your plants!",
    store_scan_pwa_desc: "Add Jaliz to your home screen to set up smart watering reminders and keep this plant healthy.",
    store_scan_register_cta: "Sign Up & Save Plant",
    store_scan_save_draft_modal_title: "Save Scanned Plant",
    store_scan_save_draft_modal_desc: "We found the plant you scanned at {store}! Do you want to save it to your garden and set up watering reminders?",
    store_scan_save_success: "Plant added to your garden!",
  },
  fa: {
    app_title: "جالیز",
    home: "خانه",
    schedule: "آبیاری و مراقبت",
    dashboard: "باغچه من",
    marketplace: "بازارچه",
    my_plants: "گیاهان من",
    nav_my_plants: "گیاهان",
    nav_schedule: "آبیاری",
    nav_marketplace: "بازارچه",
    nav_chats: "گفتگوها",
    nav_smart_detect: "تشخیص",
    welcome_title: "روزت سرشار از طراوت 🌿",
    morning_greeting: "صبح بخیر! روزت سرشار از طراوت 🌿",
    afternoon_greeting: "ظهر بخیر! وقت رسیدگی به آرامش سبز شماست 🍃",
    evening_greeting: "عصر بخیر! غروب دل‌انگیزتان بخیر 🌅",
    night_greeting: "شب بخیر! زمان استراحت گیاهان فرا رسیده 🌙",
    welcome_desc: "امروز گیاهان شما به توجه و مراقبت نیاز دارند.",
    watering_title: "برنامه آبیاری 💧",
    watering_desc: "۳ گیاه امروز منتظر رسیدگی شما هستند.",
    weather_title: "هواشناسی هوشمند باغبانی ☁️",
    weather_desc: "پیشنهادهای اختصاصی برای مراقبت از گیاهان در ۴۸ ساعت آینده.",
    analyzing: "در حال بررسی شرایط جوی... 🌬️",
    generate_btn: "دریافت مشاوره 💡",
    generating_btn: "در حال تحلیل... 💭",
    advice_prompt: "برای دریافت توصیه‌های اختصاصی گیاهانتان، کلیک کنید 🌸",
    market_title: "بازارچه سبز محله 🏘️",
    market_within: "در شعاع ۵ کیلومتری",
    contact_btn: "ارتباط در واتساپ 💬",
    away: "فاصله",
    by: "از طرف",
    add_plant: "افزودن گیاه 🪴",
    add_new_plant: "اضافه کردن عضو جدید به مجموعه 🌿",
    plant_name: "نام گیاه",
    plant_name_ph: "مثلا: برگ انجیری (مونسترا)",
    plant_type: "دسته‌بندی گیاه",
    plant_type_ph: "مثلا: گیاه آپارتمانی استوایی",
    location_type: "محیط نگهداری",
    location_indoor: "فضای داخلی (آپارتمانی) 🏠",
    location_outdoor: "فضای باز 🌳",
    light_exposure: "نیاز نوری",
    light_low: "نور کم ☁️",
    light_partial: "سایه روشن ⛅",
    light_bright: "نور غیرمستقیم 🌤️",
    light_full: "آفتاب کامل ☀️",
    pot_type: "جنس گلدان",
    pot_terracotta: "سفالی 🏺",
    pot_plastic: "پلاستیکی 🪣",
    pot_ceramic: "سرامیکی 🍵",
    pot_metal: "فلزی 🥫",
    pot_other: "سایر",
    growing_medium: "محیط رشد",
    medium_soil: "خاک 🌱",
    medium_water: "آب (هیدروپونیک) 💧",
    has_drainage: "دارای زهکشی مناسب",
    last_watered: "تاریخ آخرین آبیاری",
    last_soil_change: "آخرین تعویض خاک",
    relative_date_today: "امروز",
    relative_date_3days: "سه روز پیش",
    relative_date_week: "هفته‌ی پیش",
    watering_interval_label: "دوره آبیاری",
    watering_interval_days: "روز",
    watering_interval_locked_hint: "دوره آبیاری پیشنهادی",
    soil_change_recommendation: "توصیه تعویض خاک",
    soil_change_unknown: "ثبت نشده",
    soil_change_months_ago: "ماه پیش",
    recently_replanted: "اخیراً تعویض گلدان شده",
    plant_image: "تصویر گیاه (اختیاری) 📸",
    health_status: "وضعیت شادابی",
    health_excellent: "بسیار شاداب و سالم ✨",
    health_good: "خوب 🙂",
    health_needs_attention: "نیازمند توجه و مراقبت بیشتر 🍂",
    cancel: "انصراف",
    save: "ثبت اطلاعات گیاه 💚",
    no_plants_title: "باغچه شما منتظر است 🌱",
    no_plants_desc: "به نظر می‌رسد هنوز هیچ گیاهی به مجموعه خود اضافه نکرده‌اید. اولین گیاه خود را اضافه کنید تا با هم از آن مراقبت کنیم!",
    no_plants_cta: "افزودن اولین گیاه",
    watered_today: "امروز آبیاری شده 💧",
    share_plant: "اشتراک‌گذاری",
    share_plant_cta: "گیاهم رو شیر کن",
    share_plant_desc: "یه کارت بامزه با عکس، آخرین وضعیت و مراقبت بعدی — آماده پست در شبکه‌های اجتماعی!",
    share_plant_preparing: "در حال ساخت کارت اشتراک…",
    share_plant_success: "آماده پست! متن کپی شد و تصویر ذخیره شد.",
    share_plant_cancelled: "اشتراک‌گذاری لغو شد",
    watered_days_ago: "روز پیش آبیاری شده",
    care_tips: "نکات طلایی مراقبت",
    care_tips_ph: "توصیه‌های نگهداری...",
    watering_tips: "اصول آبیاری",
    watering_tips_ph: "زمان‌بندی و میزان آبیاری...",
    settings: "تنظیمات ⚙️",
    changelog: "تاریخچه تغییرات",
    api_key_title: "تنظیمات کلید API جمینای",
    api_key_desc: "کلید API جمینای خود را وارد کنید تا مشاوره هوشمند فعال شود.",
    api_key_label: "کلید API",
    api_key_ph: "AIzaSy...",
    fetch_models: "دریافت لیست مدل‌ها",
    fetching: "در حال دریافت...",
    select_model: "انتخاب مدل",
    token_limit: "محدودیت توکن",
    input_tokens: "ورودی",
    output_tokens: "خروجی",
    save_settings: "ذخیره تنظیمات",
    saved_successfully: "تنظیمات با موفقیت ذخیره شد!",
    theme_label: "تم برنامه",
    theme_desc: "ظاهر روشن یا تاریک برنامه را انتخاب کنید.",
    theme_light: "روشن",
    theme_dark: "تاریک",
    api_key_required: "وارد کردن کلید API برای دریافت مشاوره الزامی است.",
    user_location_title: "موقعیت مکانی شما",
    user_location_label: "شهر، کشور",
    user_location_ph: "مثال: تهران، ایران",
    // Auth
    sign_in: "ورود",
    sign_up: "ثبت‌نام",
    sign_out: "خروج",
    account: "حساب کاربری",
    admin_panel: "پنل مدیریت",
    chats: "گفتگوها",
    login_title: "خوش برگشتید",
    login_desc: "به حساب کاربری جالیز خود وارد شوید.",
    register_title: "ساخت حساب کاربری",
    register_desc: "ایمیل خود را وارد کنید و با کد یکبارمصرف تایید کنید.",
    email: "ایمیل",
    email_ph: "you@example.com",
    password: "رمز عبور",
    password_ph: "حداقل ۶ کاراکتر",
    confirm_password: "تکرار رمز عبور",
    full_name: "نام و نام خانوادگی",
    full_name_ph: "نام کامل شما",
    settings_set_password: "تنظیم رمز عبور",
    settings_set_password_desc: "اختیاری. بعد از تنظیم رمز می‌توانید با ایمیل و رمز عبور هم وارد شوید.",
    register_btn: "ساخت حساب",
    login_btn: "ورود",
    no_account: "حساب کاربری ندارید؟",
    have_account: "قبلاً ثبت‌نام کرده‌اید؟",
    login_with_password: "ورود با رمز عبور",
    login_with_otp: "ورود با رمز یکبار مصرف (OTP)",
    send_otp: "ارسال رمز یکبار مصرف",
    sending_otp: "در حال ارسال...",
    otp_sent_success: "کد تایید به ایمیل شما ارسال شد.",
    otp_code: "کد تایید (OTP)",
    otp_ph: "کد ۶ رقمی را وارد کنید",
    change_email: "تغییر ایمیل",
    login_btn_otp: "تایید و ورود",
    auth_error_invalid_credentials: "ایمیل، رمز عبور یا کد تایید اشتباه است.",
    auth_error_email_exists: "حسابی با این ایمیل قبلاً ثبت شده است.",
    auth_error_user_inactive: "این حساب کاربری غیرفعال شده است.",
    auth_error_user_not_found: "کاربر یافت نشد.",
    auth_error_weak_password: "رمز عبور باید حداقل ۶ کاراکتر باشد.",
    auth_error_invalid_email: "لطفاً یک ایمیل معتبر وارد کنید.",
    auth_error_empty_field: "لطفاً همه فیلدهای ضروری را پر کنید.",
    auth_error_password_mismatch: "رمز عبور و تکرار آن یکسان نیستند.",
    auth_error_otp_send_failed:
      "ارسال ایمیل کد تایید ممکن نشد. ایمیل را بررسی کنید یا با رمز عبور وارد شوید.",
    auth_error_generic: "خطایی رخ داد. لطفاً دوباره تلاش کنید.",
    promo_top_text: "🎁 ۲۰۰,۰۰۰ تومان هدیه ثبت‌نام و خرید اول! همین حالا ثبت‌نام کنید و هدیه خود را دریافت کنید.",
    promo_top_cta: "ثبت‌نام و دریافت هدیه",
    promo_card_title: "۲۰۰,۰۰۰ تومان هدیه خرید اول شما! 🎁",
    promo_card_desc: "تا حالا از جالیز خرید نکردید؟ همین حالا عضو شوید و برای اولین خرید خود از بازارچه، ۲۰۰,۰۰0 تومان تخفیف ویژه بگیرید.",
    promo_card_cta: "ثبت‌نام و دریافت هدیه",

    // Admin panel
    admin_title: "مدیریت کاربران",
    admin_desc: "کاربران ثبت‌شده، نقش‌ها و دسترسی‌ها را مدیریت کنید.",
    admin_search_ph: "جستجو بر اساس نام یا ایمیل…",
    admin_total_users: "کل کاربران",
    admin_active_users: "فعال",
    admin_admins: "ادمین‌ها",
    admin_col_user: "کاربر",
    admin_col_role: "نقش",
    admin_col_status: "وضعیت",
    admin_col_joined: "تاریخ عضویت",
    admin_col_actions: "عملیات",
    admin_role_admin: "ادمین",
    admin_role_user: "کاربر",
    admin_status_active: "فعال",
    admin_status_inactive: "غیرفعال",
    admin_create_user_btn: "ساخت کاربر",
    admin_action_edit: "ویرایش",
    admin_action_reset: "بازنشانی رمز",
    admin_action_delete: "حذف",
    admin_action_deactivate: "غیرفعال کردن",
    admin_action_activate: "فعال کردن",
    admin_no_users: "کاربری مطابق با جستجو یافت نشد.",
    admin_confirm_delete: "این کاربر برای همیشه حذف شود؟ این عمل قابل بازگشت نیست.",
    admin_create_title: "ساخت کاربر جدید",
    admin_create_desc: "نام، ایمیل و رمز عبور کاربر را تعیین کنید. کاربر بلافاصله می‌تواند با این رمز وارد شود.",
    admin_edit_title: "ویرایش کاربر",
    admin_edit_desc: "نام، ایمیل، نقش یا رمز عبور کاربر را تغییر دهید.",
    admin_save_user: "ذخیره کاربر",
    admin_password_optional: "برای حفظ رمز فعلی خالی بگذارید",
    admin_user_active: "کاربر فعال است",
    admin_create_success: "کاربر با موفقیت ساخته شد.",
    admin_update_success: "اطلاعات کاربر به‌روزرسانی شد.",
    admin_reset_title: "بازنشانی رمز عبور",
    admin_reset_desc: "یک رمز عبور جدید برای {name} تعیین کنید. در ورود بعدی باید از آن استفاده کند.",
    admin_reset_new_password: "رمز عبور جدید",
    admin_reset_btn: "ثبت رمز",
    admin_reset_success: "رمز عبور با موفقیت تغییر کرد.",
    admin_self_warning: "نمی‌توانید نقش یا وضعیت حساب خودتان را از اینجا تغییر دهید.",
    admin_only: "دسترسی به این بخش محدود به مدیران است.",
    go_home: "بازگشت به داشبورد",
    auth_required: "برای ادامه، لطفاً وارد حساب کاربری خود شوید 🔑",
    you_label: "(شما)",
    // Admin AI API config
    admin_ai_title: "تنظیمات API هوش مصنوعی",
    admin_ai_desc: "سرویس‌دهنده AI و کلید API را برای همه کاربران تنظیم کنید.",
    admin_ai_provider_label: "سرویس‌دهنده AI",
    admin_ai_provider_sotoon: "ستون اینتلیجنس",
    admin_ai_provider_gemini_hint: "از مدل‌های Gemini گوگل استفاده می‌کند. نیاز به کلید API گوگل دارد.",
    admin_ai_provider_sotoon_hint: "سرویس ایرانی AI (سازگار با OpenAI). بدون مشکل فیلترینگ.",
    admin_ai_provider_gapgpt: "گپ جی‌پی‌تی",
    admin_ai_provider_gapgpt_hint: "درگاه ایرانی AI (سازگار با OpenAI). دسترسی به مدل‌های GPT، Gemini و بیشتر.",
    admin_ai_key_label: "کلید API",
    admin_ai_key_ph: "AIzaSy...",
    admin_ai_key_ph_sotoon: "sk-...",
    admin_ai_key_ph_gapgpt: "gapgpt-...",
    admin_ai_fetch_models: "تایید و دریافت مدل‌ها",
    admin_ai_select_model: "مدل پیش‌فرض",
    admin_ai_save: "ذخیره تنظیمات AI",
    admin_ai_saved: "تنظیمات AI برای همه کاربران ذخیره شد!",
    admin_ai_no_key: "هنوز کلید API تنظیم نشده است.",
    // Landing page
    landing_hero_eyebrow: "دستیار مهربان گیاهان شما",
    landing_hero_title: "دیگه نگران خشک شدن گیاهت نباش.",
    landing_hero_subtitle: "جالیز قدم به قدم بهت میگه کی آب بدی و چطور از گیاهانت مراقبت کنی، به ساده‌ترین شکل ممکن.",
    landing_cta_primary: "ساخت حساب رایگان",
    landing_cta_secondary: "ورود",
    landing_hero_card_title: "نکته ساده‌ی امروز",
    landing_hero_card_line1: "مونسترای شما تشنه به نظر می‌رسه! امروز یه آبیاری خوب بهش بده.",
    landing_hero_card_line2: "آلوئه‌ورا رو کمی به پنجره نزدیک‌تر کن تا نور بیشتری بگیره.",
    landing_hero_card_badge: "راهنمایی ساده",
    landing_trust_label: "عالی برای اولین تجربه‌های نگهداری از:",
    landing_trust_chip_1: "گیاهان آپارتمانی",
    landing_trust_chip_2: "ساکولنت‌ها",
    landing_trust_chip_3: "گل‌های بالکنی",
    landing_trust_chip_4: "گیاهان دارویی",
    landing_features_eyebrow: "چرا جالیز",
    landing_features_title: "مراقبت از گیاهان، ساده‌تر از همیشه",
    landing_features_subtitle: "نیازی نیست باغبان حرفه‌ای باشی. ما همه چیز رو به ساده‌ترین شکل بهت یاد می‌دیم تا گیاهانت همیشه شاداب بمونن.",
    landing_feature_1_title: "یادآوری‌های ساده",
    landing_feature_1_desc: "بدون کلمات پیچیده و تخصصی. فقط یادآوری‌های به‌موقع برای آبیاری و نور گیاه.",
    landing_feature_2_title: "ثبت روند رشد",
    landing_feature_2_desc: "دیگه یادت نمیره کی آب دادی. یه دفترچه خاطرات ساده از گیاهت داشته باش.",
    landing_feature_3_title: "دوستان سبز پیدا کن",
    landing_feature_3_desc: "با همسایه‌های مهربون آشنا شو تا قلمه، گیاه و تجربه‌های ساده رو با هم به اشتراک بذارید.",
    landing_feature_4_title: "ساده و راحت",
    landing_feature_4_desc: "طراحی شده برای همه، با زبانی ساده و صمیمی به دو زبان فارسی و انگلیسی.",
    landing_how_eyebrow: "چطور کار می‌کند",
    landing_how_title: "در ۳ قدم ساده شروع کن",
    landing_step_1_title: "حساب کاربری بساز",
    landing_step_1_desc: "فقط ۱ دقیقه طول می‌کشه و کاملاً رایگانه.",
    landing_step_2_title: "گیاهت رو اضافه کن",
    landing_step_2_desc: "یه عکس بگیر یا اسمش رو بنویس، بقیه‌اش با ما.",
    landing_step_3_title: "توصیه‌های ساده رو انجام بده",
    landing_step_3_desc: "فقط کافیه لیست کارهای روزانه رو چک کنی تا گیاهت سرحال بمونه.",
    landing_final_cta_title: "سلامت گیاهت رو همین الان چک کن",
    landing_final_cta_subtitle: "با تشخیص هوشمند شروع کن؛ بعد اگر خواستی حساب بساز و گیاهت رو ثبت کن تا یادآوری‌ها برات فعال بشه.",
    landing_final_cta_button: "همین حالا شروع کن — رایگانه",
    landing_footer: "ساخته‌شده با عشق برای تازه‌کارها.",
    landing_slide_diag_title: "تشخیص هوشمند گیاه",
    landing_slide_diag_desc: "یه عکس بگیر تا جالیز استرس، آفت و بیماری رو پیدا کنه و راهنمای مراقبت بده.",
    landing_cta_diagnose: "شروع تشخیص هوشمند",
    landing_cta_register_plant: "ثبت‌نام و ثبت گیاه",
    landing_cta_login_hint: "قبلاً ثبت‌نام کردی؟ ورود",
    landing_cta_footer_note: "تشخیص همین الان در دسترسه. فقط وقتی بخوای گیاه رو ذخیره کنی ثبت‌نام کن.",
    landing_skip: "رد شدن",
    landing_next: "بعدی",
    landing_prev: "قبلی",
    smart_diag_guest_save_hint: "برای ذخیره این گیاه در باغچه‌ات یک حساب رایگان بساز.",
    smart_diag_opt_new_guest: "ثبت‌نام و ذخیره گیاه",
    blog: "وبلاگ",
    articles: "مقالات آموزشی",
    // Marketplace
    mp_title: "بازارچه",
    mp_subtitle: "بذر، قلمه، ابزار و محصولات را با باغبان‌های نزدیک بفروش، تبادل کن یا هدیه بده.",
    mp_post_btn: "ثبت آگهی",
    mp_view_all: "مشاهده همه",
    mp_tab_all: "همه",
    mp_tab_seed: "بذر",
    mp_tab_cutting: "قلمه",
    mp_tab_tool: "ابزار",
    mp_tab_produce: "محصولات",
    mp_tab_mine: "آگهی‌های من",
    mp_search_ph: "جستجو در آگهی‌ها… 🔍",
    mp_no_results: "نتیجه‌ای مطابق با جستجوی شما یافت نشد.",
    mp_empty_title: "بازارچه در حال حاضر خالی است",
    mp_empty_desc: "شما می‌توانید اولین نفری باشید که گیاهان، بذرها یا ابزار باغبانی خود را به اشتراک می‌گذارد 🌱",
    mp_dashboard_empty_title: "هیچ آگهی در اطراف شما ثبت نشده است",
    mp_dashboard_empty_desc: "همین حالا اولین آگهی خود را ثبت کنید! ✨",
    mp_completed_badge: "انجام شد",
    mp_type_seed: "بذر",
    mp_type_cutting: "قلمه",
    mp_type_tool: "ابزار",
    mp_type_produce: "محصول",
    mp_mode_sell: "فروش",
    mp_mode_exchange: "تبادل",
    mp_mode_free: "رایگان",
    mp_view_details: "مشاهده جزئیات",
    mp_advice_recs_title: "پیشنهاد از بازارچه",
    mp_advice_recs_view: "مشاهده در بازارچه",
    // Form
    mp_form_create_title: "ثبت آگهی جدید",
    mp_form_edit_title: "ویرایش آگهی",
    mp_field_type: "دسته‌بندی",
    mp_field_mode: "نوع آگهی",
    mp_field_title_label: "عنوان",
    mp_field_title_ph: "مثلاً: بذر گوجه فرنگی ارگانیک",
    mp_field_description_label: "توضیحات",
    mp_field_description_ph: "تعداد، وضعیت، نکات کاشت…",
    mp_field_image_label: "تصویر (اختیاری)",
    mp_field_price_label: "قیمت (تومان)",
    mp_field_price_ph: "مثلاً: ۵۰۰۰۰",
    mp_field_exchange_for_label: "در ازای",
    mp_field_exchange_for_ph: "مثلاً: بذر ریحان، قلمه گیاه دارویی",
    mp_field_location_label: "محل (اختیاری)",
    mp_field_location_ph: "مثلاً: تهران، منطقه ۵",
    mp_field_phone_label: "شماره تماس (اختیاری)",
    mp_field_phone_ph: "مثلاً: ۰۹۱۲۰۰۰۰۰۰۰",
    mp_field_phone_hint: "در پروفایلت ذخیره می‌شود و برای تماس و واتساپ روی این آگهی نمایش داده می‌شود.",
    mp_form_submit_create: "انتشار آگهی",
    mp_form_submit_save: "ذخیره تغییرات",
    mp_form_error_required: "لطفاً عنوان و توضیحات را وارد کنید.",
    mp_form_error_price: "لطفاً یک قیمت معتبر وارد کنید.",
    mp_form_error_generic: "ذخیره آگهی انجام نشد. لطفاً دوباره تلاش کنید.",
    // Details
    mp_details_owner: "ثبت‌کننده",
    mp_details_posted_at: "تاریخ ثبت",
    mp_details_completed_at: "تاریخ تکمیل",
    mp_details_no_phone: "شماره تماسی ثبت نشده",
    mp_action_complete: "علامت‌گذاری به‌عنوان انجام‌شده",
    mp_action_reopen: "بازگشایی آگهی",
    mp_action_edit: "ویرایش",
    mp_action_delete: "حذف",
    mp_action_message: "پیام",
    mp_action_call: "تماس",
    mp_action_whatsapp: "واتساپ",
    mp_action_sign_in_to_contact: "برای تماس با فروشنده وارد شوید",
    mp_confirm_delete: "آیا از حذف این آگهی اطمینان دارید؟ این عمل غیرقابل بازگشت است.",
    mp_status_active: "فعال",
    mp_status_completed: "تکمیل‌شده",
    // Chat
    mp_chat_title: "گفتگو",
    mp_chat_no_messages: "اولین پیام شما آغازگر گفتگو خواهد بود.",
    mp_chat_send: "ارسال",
    mp_chat_input_ph: "پیام خود را بنویسید…",
    mp_chat_sign_in_required: "برای ارسال پیام وارد شوید.",
    // Smart detect
    smart_detect: "تشخیص هوشمند",
    smart_diag_title: "تشخیص هوشمند بیماری",
    smart_diag_desc: "سلامت گیاه خود را با هوش مصنوعی بسنجید، مشکلات را شناسایی کنید و راهکار درمانی بگیرید.",
    smart_diag_btn: "شروع عیب‌یابی",
    smart_diag_loading: "در حال بررسی و عیب‌یابی سلامت گیاه...",
    smart_diag_result_title: "گزارش تشخیص هوشمند",
    smart_diag_health: "وضعیت سلامت تشخیص داده شده",
    smart_diag_issue: "خلاصه تشخیص هوش مصنوعی",
    smart_diag_advice: "راهکار درمانی و توصیه‌های مراقبتی",
    smart_diag_opt_new: "ثبت به عنوان گلدان جدید",
    smart_diag_opt_existing: "ثبت وضعیت برای گلدان موجود",
    smart_diag_opt_discard: "رد کردن و انصراف",
    smart_diag_select_plant: "انتخاب گیاه جهت ثبت وضعیت",
    smart_diag_save_success: "گزارش وضعیت با موفقیت ثبت شد!",
    smart_diag_new_success: "گیاه با موفقیت ثبت شد!",
    smart_diag_select_placeholder: "انتخاب گیاه...",
    smart_diag_save_log_btn: "ثبت گزارش وضعیت",
    // Profile Edit
    edit_profile: "ویرایش پروفایل",
    profile_photo: "عکس پروفایل",
    phone_number: "شماره تماس",
    phone_number_ph: "مثال: ۰۹۱۲XXXXXXX",
    profile_update_success: "پروفایل شما با موفقیت به‌روزرسانی شد!",
    change_photo: "تغییر عکس",
    remove_photo: "حذف عکس",
    // Install Prompt
    install_title: "نصب اپلیکیشن جالیز",
    install_description: "جالیز رو به صفحه اصلی گوشیت اضافه کن — دسترسی سریع، پشتیبانی آفلاین و تجربه بهتر.",
    install_button: "نصب اپلیکیشن",
    install_ios_guide: "جالیز رو در دو مرحله به صفحه اصلیت اضافه کن:",
    install_ios_step1: "اشتراک‌گذاری",
    install_ios_step2: "افزودن به Home",
    // Storefront Scan
    store_scan_welcome: "به گل‌فروشی {store} خوش آمدید! 🪴",
    store_scan_welcome_default: "به گل‌فروشی همکار جالیز خوش آمدید! 🪴",
    store_scan_subtitle: "از هر گیاهی که دوست داری عکس بگیر تا روش نگهداریش رو بهت بگم!",
    store_scan_take_photo: "گرفتن عکس یا بارگذاری تصویر",
    store_scan_analyzing: "در حال بررسی جزئیات گیاه...",
    store_scan_pwa_title: "زمان آبیاری گیاهانت رو فراموش نکن!",
    store_scan_pwa_desc: "جالیز رو به صفحه اصلی گوشیت اضافه کن تا بتونی یادآور آبیاری هوشمند براش بسازی و همیشه شاداب نگهش داری.",
    store_scan_register_cta: "عضویت در جالیز و ذخیره گیاه",
    store_scan_save_draft_modal_title: "ذخیره گیاه اسکن شده",
    store_scan_save_draft_modal_desc: "گیاهی که در گل‌فروشی {store} اسکن کرده بودید پیدا شد! آیا می‌خواهید آن را به باغچه خود اضافه کنید و یادآور آبیاری بسازید؟",
    store_scan_save_success: "گیاه با موفقیت به باغچه شما اضافه شد!",
  }
}

type TranslationKey = keyof typeof translations.en

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("fa")

  useEffect(() => {
    // Read from localStorage if available
    const saved = localStorage.getItem("jaliz-lang") as Language
    if (saved && (saved === "en" || saved === "fa")) {
      const timer = window.setTimeout(() => setLanguage(saved), 0)
      return () => window.clearTimeout(timer)
    }
  }, [])

  useEffect(() => {
    // Save preference and update document direction
    localStorage.setItem("jaliz-lang", language)
    document.documentElement.dir = language === "fa" ? "rtl" : "ltr"
    document.documentElement.lang = language

    if (language === "fa") {
      document.body.style.fontFamily = "var(--font-vazirmatn), ui-sans-serif, system-ui, sans-serif"
      document.documentElement.style.setProperty("--font-sans", "var(--font-vazirmatn)")
    } else {
      document.body.style.fontFamily = ""
      document.documentElement.style.setProperty("--font-sans", "var(--font-geist-sans)")
    }
  }, [language])

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key]
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
